python2Packages.numpydoc: disable python2, abandonded
```
  Traceback (most recent call last):
    File "nix_run_setup", line 8, in <module>
      exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
    File "setup.py", line 11, in <module>
      raise RuntimeError("Python version >= 3.5 required.")
  RuntimeError: Python version >= 3.5 required.
  builder for '/nix/store/i3wyagaqjhq2bbf184qlw886v4mvda29-python2.7-numpydoc-1.0.0.drv' failed with exit code 1
```